//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWebSite.CarManagementServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarManagementServiceReference.IVehicleManagementService")]
    public interface IVehicleManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/InsertCar", ReplyAction="http://tempuri.org/IVehicleManagementService/InsertCarResponse")]
        string InsertCar(CarRentalServices.CarModel car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/InsertCar", ReplyAction="http://tempuri.org/IVehicleManagementService/InsertCarResponse")]
        System.Threading.Tasks.Task<string> InsertCarAsync(CarRentalServices.CarModel car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/RetrieveCarDetails", ReplyAction="http://tempuri.org/IVehicleManagementService/RetrieveCarDetailsResponse")]
        CarRentalServices.CarModel RetrieveCarDetails(int carId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/RetrieveCarDetails", ReplyAction="http://tempuri.org/IVehicleManagementService/RetrieveCarDetailsResponse")]
        System.Threading.Tasks.Task<CarRentalServices.CarModel> RetrieveCarDetailsAsync(int carId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/UpdateCarDetails", ReplyAction="http://tempuri.org/IVehicleManagementService/UpdateCarDetailsResponse")]
        string UpdateCarDetails(int carId, CarRentalServices.CarModel car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/UpdateCarDetails", ReplyAction="http://tempuri.org/IVehicleManagementService/UpdateCarDetailsResponse")]
        System.Threading.Tasks.Task<string> UpdateCarDetailsAsync(int carId, CarRentalServices.CarModel car);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/DeleteCarRecords", ReplyAction="http://tempuri.org/IVehicleManagementService/DeleteCarRecordsResponse")]
        string DeleteCarRecords(int carId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/DeleteCarRecords", ReplyAction="http://tempuri.org/IVehicleManagementService/DeleteCarRecordsResponse")]
        System.Threading.Tasks.Task<string> DeleteCarRecordsAsync(int carId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/AvailableCars", ReplyAction="http://tempuri.org/IVehicleManagementService/AvailableCarsResponse")]
        CarRentalServices.CarModel[] AvailableCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/AvailableCars", ReplyAction="http://tempuri.org/IVehicleManagementService/AvailableCarsResponse")]
        System.Threading.Tasks.Task<CarRentalServices.CarModel[]> AvailableCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/Booking", ReplyAction="http://tempuri.org/IVehicleManagementService/BookingResponse")]
        string Booking(int numdays, CarRentalServices.CustomerModel customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleManagementService/Booking", ReplyAction="http://tempuri.org/IVehicleManagementService/BookingResponse")]
        System.Threading.Tasks.Task<string> BookingAsync(int numdays, CarRentalServices.CustomerModel customer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleManagementServiceChannel : CarRentalWebSite.CarManagementServiceReference.IVehicleManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleManagementServiceClient : System.ServiceModel.ClientBase<CarRentalWebSite.CarManagementServiceReference.IVehicleManagementService>, CarRentalWebSite.CarManagementServiceReference.IVehicleManagementService {
        
        public VehicleManagementServiceClient() {
        }
        
        public VehicleManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertCar(CarRentalServices.CarModel car) {
            return base.Channel.InsertCar(car);
        }
        
        public System.Threading.Tasks.Task<string> InsertCarAsync(CarRentalServices.CarModel car) {
            return base.Channel.InsertCarAsync(car);
        }
        
        public CarRentalServices.CarModel RetrieveCarDetails(int carId) {
            return base.Channel.RetrieveCarDetails(carId);
        }
        
        public System.Threading.Tasks.Task<CarRentalServices.CarModel> RetrieveCarDetailsAsync(int carId) {
            return base.Channel.RetrieveCarDetailsAsync(carId);
        }
        
        public string UpdateCarDetails(int carId, CarRentalServices.CarModel car) {
            return base.Channel.UpdateCarDetails(carId, car);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCarDetailsAsync(int carId, CarRentalServices.CarModel car) {
            return base.Channel.UpdateCarDetailsAsync(carId, car);
        }
        
        public string DeleteCarRecords(int carId) {
            return base.Channel.DeleteCarRecords(carId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCarRecordsAsync(int carId) {
            return base.Channel.DeleteCarRecordsAsync(carId);
        }
        
        public CarRentalServices.CarModel[] AvailableCars() {
            return base.Channel.AvailableCars();
        }
        
        public System.Threading.Tasks.Task<CarRentalServices.CarModel[]> AvailableCarsAsync() {
            return base.Channel.AvailableCarsAsync();
        }
        
        public string Booking(int numdays, CarRentalServices.CustomerModel customer) {
            return base.Channel.Booking(numdays, customer);
        }
        
        public System.Threading.Tasks.Task<string> BookingAsync(int numdays, CarRentalServices.CustomerModel customer) {
            return base.Channel.BookingAsync(numdays, customer);
        }
    }
}
